### ISSUE TITLE
Player doesn't get removed from the party when leaving the server

### ISSUE THREAD

**Issue by Aboshxm2** [Diduhless/Parties#16]
when a party member leave the server, he doesn't get kicked from the party, that's lead to some crashes like trying to kick offline player or trying to promote offline player.

[Fri_Jul_15-15.33.50-UTC_2022.log](https://github.com/Diduhless/Parties/files/9122411/Fri_Jul_15-15.33.50-UTC_2022.log)

Sorry my language is not that well, English is not my mother tongue

**Comment by pretendlake** [comment]
Thank you for reporting!
