### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by NeturCrafter** [Diduhless/Parties#18]
Crash when you use /transferserver

**Comment by pretendlake** [comment]
@NetureCrafter Could you send me the crash log?

**Comment by NeturCrafter** [comment]
[12:15:14.813] [Server thread/CRITICAL]: Error: "Call to a member function getMembers() on null" (EXCEPTION) in "plugins/Parties (1).phar/src/diduhless/parties/listener/ConfigurationListener" at line 73
--- Stack trace ---
  #0 pmsrc/src/event/RegisteredListener(60): diduhless\parties\listener\ConfigurationListener->onTransfer(object pocketmine\event\player\PlayerTransferEvent#128248)
  #1 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerTransferEvent#128248)
  #2 pmsrc/src/player/Player(2033): pocketmine\event\Event->call()
  #3 pmsrc/src/command/defaults/TransferServerCommand(57): pocketmine\player\Player->transfer(string[15] play.server.net, int 19133)
  #4 pmsrc/src/command/SimpleCommandMap(205): pocketmine\command\defaults\TransferServerCommand->execute(object pocketmine\player\Player#26490, string[14] transferserver, array[2])
  #5 pmsrc/src/Server(1446): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#26490, string[36] transferserver play.server.net 19133)
  #6 pmsrc/src/player/Player(1410): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#26490, string[36] transferserver play.server.net 19133)
  #7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(759): pocketmine\player\Player->chat(string[37] /transferserver play.server.net 19133)
  #8 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(51): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#128222)
  #9 pmsrc/src/network/mcpe/NetworkSession(392): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#118979)
  #10 pmsrc/src/network/mcpe/NetworkSession(355): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#128222, string[58] M%/transferserver play.server.net 19133.z@..i..X...w.q\...)
