### ISSUE TITLE
PM5

### ISSUE THREAD

**Issue by Chaosleo64** [Diduhless/Parties#20]
Nice Plugin, can u update to PM5?

**Comment by pretendlake** [comment]
Hello Chaos, I'm quite busy right now, and I don't have time to actively maintain this project, however, feel free to make a pull request updating the plugin to PM5, and I will merge it, otherwise, I'll try to get it done in the next month.

**Comment by Chaosleo64** [comment]
Hello, thanks for the answer. Unfortunately I can't code or recode anything like plugins, so it would be nice if you would update it.

**Comment by Sergittos** [comment]
Updated in 2.0.3
